### ISSUE TITLE
node_modules\jscrambler\node_modules\q\q.js:128 Exception

### ISSUE THREAD

**Issue by newtonianb** [jscrambler/gulp-jscrambler#2]
I tried to integrate this into my gulp task which does

- coffee compilation
- jscrambler
- gulp.dest

and I get this error 
```
C:\prj\b\node_modules\gulp-jscrambler\node_modules\jscrambler\node_modules\q\q.js:128
                    throw e;
                          ^
[object Object]
```

When I added
```
            .pipe(jscrambler({
                keys: {
                    accessKey: 'mykey,
                    secretKey: 'mysecretkey'
                },
                deleteProject: true
            }))
```

**Comment by magalhas** [comment]
I've just ran the basic unit test that it's implemented and everything seems to be working. Are you a premium user of JScrambler? Do you have a detailed stack trace of the error?

**Comment by newtonianb** [comment]
Hi @magalhas I actually also just got it working but not the way I wanted. 

I wanted to have this jscrambler chained after my coffeescript compilation pipe and this is when I got the error. However when I ran the scrambler on the compiled JS files then it did work.

Is this supposed to work if I have a coffeescript compile step just above it?

**Comment by magalhas** [comment]
It should work. There's probably a bug in the gulp task. I'll take a further look ASAP.

**Comment by newtonianb** [comment]
It seems I only get the error if I try to call jscrambler BEFORE I call my concat task
```.pipe($.concat(outputName))```

If I call jscrambler after my concat tasks then it completes without error, is this expected?

**Comment by newtonianb** [comment]
oh my goodness! I finally found the problem and I'm quite annoyed it took me all this time because the error had no clarity at all.
I went into the file that threw the error at ``C:\prj\b\node_modules\gulp-jscrambler\node_modules\jscrambler\node_modules\q\q.js`` and right above it I ran console.log(e) and I got this message

```
{ error: 400,
  message: 'Free edition is limited to 25 files. Please visit jscrambler.com and upgrade your subscription to increase the limit.' }
```
